---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
  - name: cf-deployment
  - name: deployments-routing
  - name: istio-release-ci
  - name: source1
    optional: true
  - name: source2
    optional: true

outputs:
  - name: merged-operations

params:
  ENVIRONMENT:
  SOURCE1_DIR: ~
  SOURCE2_DIR: ~

run:
  path: istio-release-ci/ci/tasks/merge-ops-files/task
