---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-deployment-concourse-tasks

inputs:
  - name: deployments-routing
  - name: istio-release-ci

run:
  path: istio-release-ci/ci/tasks/bosh2-command/task

params:
  NUMBER_OF_RUNS:
  ENVIRONMENT:
  DEPLOYMENT:
  COMMAND:
