---
image_resource:
  type: docker-image
  source: { repository: c2cnetworking/small-git }

platform: linux

inputs:
  - name: istio-release
  - name: istio-release-ci

outputs:
  - name: release-notes

run:
  path: istio-release-ci/ci/tasks/build-istio-release-notes/task

