---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/cf-routing-pipeline

inputs:
- name: istio-release
- name: istio-release-ci

run:
  path: istio-release-ci/ci/tasks/istio-release-tests/task
  user: root
