#!/bin/bash

set -euo pipefail

ROOT="$(cd "$(dirname "${0}")/../../.." && pwd)"
export GOPATH="${ROOT}"
export PATH="${GOPATH}/bin:${PATH}"

go get github.com/onsi/ginkgo/ginkgo

"${ROOT}"/scripts/test
